### Generate Computational Graph

In [1]:
import tensorflow as tf
print (tf.__version__)

/Users/z001f64/python3env/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


1.7.0


In [2]:
a=2
b=3
x=tf.add(a,b)

In [3]:
with tf.Session() as sess:
    s = sess.run(x)

In [4]:
print(s)

5


* Constant values are stored in the graph definition
* Sessions allocate memory to store variable values

### Normal Loading vs Lazy Loading

In [5]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf 

######################################## 
## NORMAL LOADING                     ##
## print out a graph with 1 Add node  ## 
########################################

x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x, y)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter('graphs/normal_loading', sess.graph)
    for _ in range(10):
        sess.run(z)
    print(tf.get_default_graph().as_graph_def())
    writer.close()

########################################## 
## LAZY LOADING                         ##
## print out a graph with 10 Add nodes  ## 
##########################################

x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter('graphs/lazy_loading', sess.graph)
    for _ in range(10):
        sess.run(tf.add(x, y))
    print(tf.get_default_graph().as_graph_def()) 
    writer.close()

node {
  name: "Add/x"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "Add/y"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 3
      }
    }
  }
}
node {
  name: "Add"
  op: "Add"
  input: "Add/x"
  input: "Add/y"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "x/initial_value"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 10
      }
    }
  }
}
node {
  name: "x"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: "

### Tensor Flow Variables and Constants

In [6]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf

# Example 1: feed_dict with placeholder

# a is a placeholderfor a vector of 3 elements, type tf.float32
a = tf.placeholder(tf.float32, shape=[3])
b = tf.constant([5, 5, 5], tf.float32)
c = tf.add(a,b)
writer = tf.summary.FileWriter('graphs/addition', sess.graph)
with tf.Session() as sess:
    Sum=sess.run(c, {a:[3,2,6]})
    print(Sum)
writer.close()

[ 8.  7. 11.]


### Visualize Tensorflow

In [7]:
import tensorflow as tf

In [8]:
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a,b)

In [9]:
writer = tf.summary.FileWriter("./graphs", sess.graph)

In [11]:
with tf.Session() as sess:
    print (sess.run(x))

5


### More constants

In [13]:
a=tf.constant([2,2], name='a')
b=tf.constant([[0, 1], [2,3]], name="b")
x=tf.add(a,b, name="add")
y=tf.multiply(a,b, name="prod")
with tf.Session() as sess:
    x,y = sess.run([x,y])
    print (x,y)

[[2 3]
 [4 5]] [[0 2]
 [4 6]]


In [17]:
a=tf.constant([2,2], name='a')
b=tf.constant([[0, 1], [2,3]], name="b")
x=tf.add(a,b, name="add")
with tf.Session() as sess:
    sess.run(x)
    print (sess.run(x))

[[2 3]
 [4 5]]


### Tensors filled with specific value

In [22]:
x=tf.ones(4, dtype=tf.float32, name=None)

In [23]:
with tf.Session() as sess:
    print (sess.run(x))

[1. 1. 1. 1.]


In [25]:
y=tf.fill([4,5], 3)
with tf.Session() as sess:
    print (sess.run(y))

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [26]:
import numpy as np
np.random.random(1)

array([0.59477038])

In [41]:
x=tf.fill([3,4], 6)

In [42]:
with tf.Session() as sess:
    print (sess.run(x))

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [44]:
z=tf.matmul(x,y)

In [45]:
with tf.Session() as sess:
    print (sess.run(z))

[[72 72 72 72 72]
 [72 72 72 72 72]
 [72 72 72 72 72]]


In [46]:
b=tf.fill([4], 3)

In [47]:
a=tf.placeholder(tf.float32, [4])